/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NameAvailabilityResult = IDL.Record({
  'isAvailable' : IDL.Bool,
  'message' : IDL.Text,
});
export const FormationOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'businessName' : IDL.Text,
  'formationType' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FormationOrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'businessName' : IDL.Text,
  'formationType' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const SubmissionResponse = IDL.Record({
  'orderId' : IDL.Nat,
  'confirmationMessage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkNameAvailability' : IDL.Func(
      [IDL.Text],
      [NameAvailabilityResult],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(FormationOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(FormationOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFormationOrder' : IDL.Func(
      [FormationOrderInput],
      [SubmissionResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NameAvailabilityResult = IDL.Record({
    'isAvailable' : IDL.Bool,
    'message' : IDL.Text,
  });
  const FormationOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'additionalDetails' : IDL.Text,
    'businessName' : IDL.Text,
    'formationType' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FormationOrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'additionalDetails' : IDL.Text,
    'businessName' : IDL.Text,
    'formationType' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const SubmissionResponse = IDL.Record({
    'orderId' : IDL.Nat,
    'confirmationMessage' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkNameAvailability' : IDL.Func(
        [IDL.Text],
        [NameAvailabilityResult],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(FormationOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(FormationOrder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFormationOrder' : IDL.Func(
        [FormationOrderInput],
        [SubmissionResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };